### ISSUE TITLE
reflectx: Go 1.6 changes

### ISSUE THREAD

**Issue by woniu369** [zeebo/bencode#17]
https://github.com/zeebo/bencode/blob/a0e3ea0de8603e1ed5afdedf6ab4ab564a4a880f/decode.go#L412

f.PkgPath != "" && !f.Anonymous

http://tip.golang.org/doc/go1.6#reflect

**Comment by zeebo** [comment]
Hmm.. seems like doing that will cause gccgo for prior to 1.6 to be broken. Seems like a small enough use case that I'm ok with it.
