### ISSUE TITLE
Add Unmarshaler/Marshaler interface support

### ISSUE THREAD

**Issue by GlenDC** [zeebo/bencode#22]
Currently it is not possible to control how a type is to be encoded (and decoded again). However similar to other packages (YAML/JSON), it would be quite useful to be able to control this for certain types.

As you seem to take inspiration from the std JSON package I think we can keep the Marshaler as simple as:

```go
// Marshaler is the interface implemented by types
// that can marshal themselves into valid bencode.
type Marshaler interface {
	MarshalBencode() ([]byte, error)
}
```

I think implementing that could be as simple as:

```diff
diff --git a/encode.go b/encode.go
index eac347a..3ca2e40 100644
--- a/encode.go
+++ b/encode.go
@@ -29,6 +29,12 @@ func (p sortFields) Less(i, j int) bool {
 }
 func (p sortFields) Swap(i, j int) { p[i], p[j] = p[j], p[i] }
 
+// Marshaler is the interface implemented by types
+// that can marshal themselves into valid bencode.
+type Marshaler interface {
+	MarshalBencode() ([]byte, error)
+}
+
 //An Encoder writes bencoded objects to an output stream.
 type Encoder struct {
 	w io.Writer
@@ -81,6 +87,18 @@ func encodeValue(w io.Writer, val reflect.Value) error {
 		return nil
 	}
 
+	// marshal a type using the Marshaler type
+	// if it implements that interface.
+	if marshaler, ok := v.Interface().(Marshaler); ok {
+		bytes, err := marshaler.MarshalBencode()
+		if err != nil {
+			return err
+		}
+
+		_, err = w.Write(bytes)
+		return err
+	}
+
 	//send in a raw message if we have that type
 	if rm, ok := v.Interface().(RawMessage); ok {
 		_, err := io.Copy(w, bytes.NewReader(rm))
```

But feel free to correct me, in case I'm missing any complexities though.

For the Unmarshaler things get however a bit more complicated. I would propose to again keep the interface as simple as:

```go
// Unmarshaler is the interface implemented by types that can unmarshal
// a bencode description of themselves.
// The input can be assumed to be a valid encoding of a bencode value.
// UnmarshalBencode must copy the bencode data if it wishes to retain the data after returning.
type Unmarshaler interface {
	UnmarshalBencode([]byte) error
}
```

However implementing it is a bit more complicated than I had imagined, due to the fact that the code doesn't seem to have taken that possibility into account. The std `encoding/json` package seems to resolve this by having a handy function available called `next()` which returns the next available JSON value from the available buffer, however such a utility function doesn't seem to be available in your decoder.

So perhaps you have an idea on how we could resolve this?

Thank you for providing this package though, a couple of months ago I was almost implementing my own bencode package from scratch, until I found yours, so this saved me a lot of work, for which lots of thanks! The package works great, But I now have a scenario where I could really use the possibility to provide my own encode/decode logic (using a marshaler/unmarshaler), such that I can encode my struct as a custom string value rather than a dictionary.

**Comment by zeebo** [comment]
One hack could be to when encountering an Unmarshaler, to instead decode into a RawMessage and then pass the []byte to it. That would get the functionality in quickly, and we can iterate on performance improvements if necessary.

**Comment by GlenDC** [comment]
Oh didn't know that would be a possibility. I guess I don't understand the code of this library well enough (yet) to think of this. If this hack ensures that the `Unmarshaler` only receives the next value, such that the other data (the data coming after that next value) gets parsed by the parent (which owns that `Unmarshaler`), than I suppose that could work for now.

I'll try this approach and let you know once I did. I suppose if that works than this would be good enough for me now. Performance isn't really a worry for me as I don't really encode/decode in a performance-critical location at the moment.

However other users might want this to be performant as well, in which case there might be a refactoring needed of the decode code. So If we go for this hack, we should probably open a new issue afterwards which aims to make this new functionality/API also performant.

Thank you for the quick response though, highly appreciated! :)

**Comment by zeebo** [comment]
I think you'll need to do it inside the Decoder itself; specifically, the `(*Decoder).decodeInto` call. I'm not very sure on the details anymore but I don't think the Decoder guarantees minimal byte reads from the underlying reader (in other words, it buffers), so creating a new Decoder may cause it to read more and discard some bytes. I started this code about 6 years ago (!!) so I've forgotten everything I once knew. :)

RawMessage itself is pretty inefficient in implementation: it decodes into an `interface{}` and keeps track of the bytes it read. I imagine we could speed both up by sharing some code to just read the minimal number of bytes necessary for a complete value.

Thank you for contributing :)
