### ISSUE TITLE
ensure encoding works with pointer receivers well

### ISSUE THREAD

**Issue by zeebo** [zeebo/bencode#28]
we need to be careful around our usage of indirect and checking if the value implements some interface during encoding. i suspect there are some bugs.

**Comment by GlenDC** [comment]
I suppose this also applies to the original `RawMessage` "cast", @zeebo?

**Comment by zeebo** [comment]
yeah i think so. i think we just need to rethink the top of encode and decode.

specifically, maybe we have to extend indirect to check for interfaces at every level and return whichever as early as possible...

**Comment by GlenDC** [comment]
Sounds like a good idea indeed. I'll do some research and think about it when I get to it.

**Comment by GlenDC** [comment]
@zeebo my solution can be found as PR #29.
