### ISSUE TITLE
There are some mistake in decode_test.go.

### ISSUE THREAD

**Issue by neoql** [zeebo/bencode#33]
code at https://github.com/zeebo/bencode/blob/master/decode_test.go#L241 and https://github.com/zeebo/bencode/blob/master/decode_test.go#L242 should be
```go
{"d1:Yi10e1:X1:a3:zff1:ce", new(dT), dT{}, true, true},
{"d3:zff1:c1:Yi10e1:X1:ae", new(dT), dT{}, true, true},
```

**Comment by zeebo** [comment]
Fixed! Thanks.
